# Generated by Django 4.1.7 on 2023-03-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backplat', '0002_rename_subject_id_teachersubject_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='assignment_id',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='student_id',
            new_name='student',
        ),
    ]
