# Generated by Django 4.1.7 on 2023-04-06 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backplat', '0003_rename_group_id_assignment_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('teacher', 'subject')},
        ),
    ]
